apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo-k8s
  labels:
    app: docker-demo-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-demo-k8s
  template:
    metadata:
      labels:
        app: docker-demo-k8s
    spec:
      containers:
      - name: docker-demo-k8s
        image: kapilyadav2076/docker-demo
        ports:
        - containerPort: 8081